### ISSUE TITLE
使用场景

### ISSUE THREAD

**Issue by transtone** [miaolz123/vue-helmet#1]
请问可否配合 vue-router 使用，当切换链接的时候，根据链接的参数同时修改 head 的内容？react-helmet 是可以的，例子：https://github.com/mattdennewitz/react-helmet-example

 如果可以，请添加类似 example，或者在主页 readme 中说明，谢谢。

更重要的是这里不能使用 script，而 https://github.com/nfl/react-helmet 是可以的。像百度地图这样的外部调用的js，配合 helmet 用起来才方便。

**Comment by miaolz123** [comment]
- :white_check_mark: vue-router & vue-helmet Example: https://github.com/miaolz123/vue-helmet#example
- :white_check_mark: scripts: https://github.com/miaolz123/vue-helmet#props

**Comment by transtone** [comment]
非常棒！
demo中的 `<vue-helmet />` 改成 `<vue-helmet></vue-helmet>` 是不是更好点

**Comment by miaolz123** [comment]
确实<vue-helmet></vue-helmet>更规范也是推荐的写法，昨天上传代码前我纠结过这一点，最后掷硬币决定了这个~
