### ISSUE TITLE
使用Vue.use(VueHelmet)安装插件会报错

### ISSUE THREAD

**Issue by LS1231** [miaolz123/vue-helmet#5]
"vue": "^1.0.21"

![image](https://cloud.githubusercontent.com/assets/5620625/16791804/fa4e724c-48f4-11e6-9fce-408443ad5f99.png)

**Comment by miaolz123** [comment]
你好，谢谢你的建议，可能是我写的使用说明误导了你~

`VueHelmet`只有在通过**独立加载**（直接在HTML里面引入`vue-helmet.js`文件）的时候是作为插件使用的，这个时候配合`Vue.use(VueHelmet)`可以注册为全局插件使用。这样是可以正常工作的，但是我个人觉得不是更高效的使用方法，因为这个时候其实可以在HTML里面自定义Head了，显得多此一举。

我个人猜测，大部分用户应该都是通过NPM安装的方式局部使用`VueHelmet`的，这个时候`VueHelmet`其实是一个组件，正确的使用方法应该是`Vue.component('vue-helmet', VueHelmet)`注册为全局组件，或者在一个组件里面的`components`内部作为局部组件出现。

还有问题的话可以继续留言，谢谢～

相关资料：
- [全局组件](http://vuejs.org.cn/guide/components.html#u6CE8_u518C)
- [局部组件](http://vuejs.org.cn/guide/components.html#局部注册)
