### ISSUE TITLE
Invalid self-closing tag:<vue-helmet title='xxx' />

### ISSUE THREAD

**Issue by lowesyang** [miaolz123/vue-helmet#6]
I've wrote code according to the example and build the .vue files with webpack, but get the error "invalid self-closing tag". And the building passed after using closing tag.
![image](https://cloud.githubusercontent.com/assets/10328169/18578015/12ec58a6-7c20-11e6-82f5-a30749b67f40.png)

**Comment by miaolz123** [comment]
Pleace write like this, which is different from React

```
<vue-helmet title='XXX'></vue-helmet>
```
