### ISSUE TITLE
这个插件会一直更新吗

### ISSUE THREAD

**Issue by gengxuelei** [miaolz123/vue-helmet#7]
在已经有https://github.com/ktquez/vue-head的情况下为神马要再造一个轮子呢，
是vue-head有什么不满足业务的吗，
选择恐惧症弱弱问一下，这个插件会更新吗，还是写着练手的

**Comment by miaolz123** [comment]
- 我当时确实没发现`vue-head`这个插件(PS:我个人看到的`vue-head`的发布时间是晚于`vue-helmet`的)
- `vue-head`大概看了一下，挺好的，完全可以满足当时我设想的业务场景
- 如有必要会更新，是写着练手的
