### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by theothersideofgod** [miaolz123/vue-helmet#8]
#vue.runtime.esm.js?9214:567 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueHelmet>
       <App> at src\App.vue
         <Root>

-------------------------------------------------------------------------------

<template>
  <div>
    <vue-helmet :scripts="[{'type': 'text/javascript', 'src': 'http://abc.xyz/filename.js'}]"></vue-helmet>
    <router-view />
  </div>
</template>

<script>
/*
 * Root component
 */
import VueHelmet from 'vue-helmet'
export default {
  components: {
    VueHelmet
  }
}
</script>

<style></style>

**Comment by bazingaedward** [comment]
please replace ready with mount in vuehelmet.js, for the error above!
